export const ADMIN_SECTIONS = [
  {
    id: "meta",
    title: "Names & App Info",
    description: "Her name, your name, dates, landing copy",
    category: "Settings",
    type: "meta",
  },
  {
    id: "dailyMessages",
    title: "Daily Messages",
    description: "One note for each day of the month",
    category: "For You",
    type: "stringList",
    path: "dailyMessages",
    itemLabel: "Message",
  },
  {
    id: "reasons",
    title: "Reasons I Love You",
    description: "Carousel of reasons",
    category: "For You",
    type: "stringList",
    path: "reasons",
    itemLabel: "Reason",
  },
  {
    id: "compliments",
    title: "Compliments",
    description: "Random compliment machine",
    category: "For You",
    type: "stringList",
    path: "compliments",
    itemLabel: "Compliment",
  },
  {
    id: "loveNotes",
    title: "Love Jar Notes",
    description: "Notes in the love jar",
    category: "For You",
    type: "stringList",
    path: "loveNotes",
    itemLabel: "Note",
  },
  {
    id: "openWhen",
    title: "Open When Letters",
    description: "Letters for different moods",
    category: "For You",
    type: "objectList",
    path: "openWhen",
    fields: [
      { key: "label", label: "Label", type: "text" },
      { key: "message", label: "Message", type: "textarea" },
    ],
  },
  {
    id: "timeline",
    title: "Our Story Timeline",
    description: "Relationship milestones",
    category: "Together",
    type: "objectList",
    path: "timeline",
    fields: [
      { key: "date", label: "Date label", type: "text" },
      { key: "eventDate", label: "Event date", type: "date" },
      { key: "title", label: "Title", type: "text" },
      { key: "desc", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "bucketList",
    title: "Bucket List",
    description: "Adventures to do together",
    category: "Together",
    type: "stringList",
    path: "bucketList",
    itemLabel: "Item",
  },
  {
    id: "dateIdeas",
    title: "Date Ideas",
    description: "Ideas for your next date",
    category: "Together",
    type: "stringList",
    path: "dateIdeas",
    itemLabel: "Date idea",
  },
  {
    id: "herFavorites",
    title: "Her Favorites",
    description: "Things she loves",
    category: "Together",
    type: "objectList",
    path: "herFavorites",
    fields: [
      { key: "thing", label: "Thing", type: "text" },
      { key: "note", label: "Note", type: "textarea" },
    ],
  },
  {
    id: "moodResponses",
    title: "Mood Check-in",
    description: "Responses for each mood",
    category: "Together",
    type: "moodMap",
    path: "moodResponses",
  },
  {
    id: "quizQuestions",
    title: "Love Quiz",
    description: "Quiz questions and answers",
    category: "Games",
    type: "quizList",
    path: "quizQuestions",
  },
  {
    id: "wheelPrizes",
    title: "Wheel & Dice Prizes",
    description: "Spin wheel / dice rewards",
    category: "Games",
    type: "stringList",
    path: "wheelPrizes",
    itemLabel: "Prize",
  },
  {
    id: "scratchPrizes",
    title: "Scratch Prizes",
    description: "Scratch card rewards",
    category: "Games",
    type: "stringList",
    path: "scratchPrizes",
    itemLabel: "Prize",
  },
  {
    id: "truths",
    title: "Truth Questions",
    description: "Truth or dare — truths",
    category: "Games",
    type: "stringList",
    path: "truths",
    itemLabel: "Truth",
  },
  {
    id: "dares",
    title: "Dare Challenges",
    description: "Truth or dare — dares",
    category: "Games",
    type: "stringList",
    path: "dares",
    itemLabel: "Dare",
  },
  {
    id: "wouldYouRather",
    title: "Would You Rather",
    description: "Cute either-or questions",
    category: "Games",
    type: "objectList",
    path: "wouldYouRather",
    fields: [
      { key: "a", label: "Option A", type: "text" },
      { key: "b", label: "Option B", type: "text" },
      { key: "reaction", label: "Reaction", type: "textarea" },
    ],
  },
  {
    id: "memorySymbols",
    title: "Memory Match Symbols",
    description: "Emoji pairs for memory game",
    category: "Games",
    type: "stringList",
    path: "memorySymbols",
    itemLabel: "Emoji",
  },
  {
    id: "heartRushMessages",
    title: "Heart Rush Messages",
    description: "Score tier messages",
    category: "Games",
    type: "objectList",
    path: "heartRushMessages",
    fields: [
      { key: "minTaps", label: "Min taps", type: "number" },
      { key: "message", label: "Message", type: "textarea" },
    ],
  },
  {
    id: "secretHeart",
    title: "Secret Heart",
    description: "Easter egg tap messages",
    category: "Extras",
    type: "secretHeart",
    path: "secretHeart",
  },
  {
    id: "games",
    title: "Games List",
    description: "Game cards on home & games page",
    category: "Navigation",
    type: "objectList",
    path: "games",
    fields: [
      { key: "to", label: "Route", type: "text" },
      { key: "icon", label: "Icon name", type: "text" },
      { key: "title", label: "Title", type: "text" },
      { key: "desc", label: "Description", type: "textarea" },
      { key: "color", label: "Color class", type: "text" },
      { key: "previewLabel", label: "Preview label (optional)", type: "text" },
    ],
  },
  {
    id: "homeSections",
    title: "Home Sections",
    description: "Home page card groups (JSON)",
    category: "Navigation",
    type: "json",
    path: "homeSections",
  },
  {
    id: "navigation",
    title: "Navigation",
    description: "Nav links (JSON)",
    category: "Navigation",
    type: "json",
    path: "navigation",
  },
];

export function getSectionById(id) {
  return ADMIN_SECTIONS.find((section) => section.id === id);
}

export function getSectionsByCategory() {
  return ADMIN_SECTIONS.reduce((groups, section) => {
    if (!groups[section.category]) groups[section.category] = [];
    groups[section.category].push(section);
    return groups;
  }, {});
}
